[package]
name         = "trinity-signer"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true

[dependencies]
trinity-types = { path = "../trinity-types" }
trinity-keystore = { path = "../trinity-keystore" }
trinity-verify = { path = "../trinity-verify" }
bitcoin = { workspace = true }
argon2 = { workspace = true }
subtle = { workspace = true }
zeroize = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
