[package]
name         = "trinity-keystore"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true

[dependencies]
trinity-types = { path = "../trinity-types", version = "0.1.0" }
zeroize = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
