[package]
name         = "trinity-transport"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true

[dependencies]
trinity-types = { path = "../trinity-types" }
bitcoin = { workspace = true }
bbqr = { workspace = true }
ur = { workspace = true }
thiserror = { workspace = true }
