[package]
name         = "trinity-chain"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true

[dependencies]
trinity-types = { path = "../trinity-types" }
bdk_core = { workspace = true }
bitcoin = { workspace = true }
thiserror = { workspace = true }
