[package]
name         = "trinity-types"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true

[dependencies]
zeroize = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
trybuild = { workspace = true }
proptest = { workspace = true }
